In [2]:
import pandas as pd

In [3]:
#loading the dataset
df = pd.read_csv('processed/knot_tying/Knot_Tying_B001.csv')

In [23]:
#print the dataset (works in notebook)
df

,MASTER_LEFT_POS_X,MASTER_LEFT_POS_Y,MASTER_LEFT_POS_Z,MASTER_LEFT_ROT_R11,MASTER_LEFT_ROT_R12,MASTER_LEFT_ROT_R13,MASTER_LEFT_ROT_R21,MASTER_LEFT_ROT_R22,MASTER_LEFT_ROT_R23,MASTER_LEFT_ROT_R31,MASTER_LEFT_ROT_R32,MASTER_LEFT_ROT_R33,MASTER_LEFT_LIN_VEL_X,MASTER_LEFT_LIN_VEL_Y,MASTER_LEFT_LIN_VEL_Z,MASTER_LEFT_ROT_VEL_X,MASTER_LEFT_ROT_VEL_Y,MASTER_LEFT_ROT_VEL_Z,MASTER_LEFT_GRIPPER_ANGLE,MASTER_RIGHT_POS_X,MASTER_RIGHT_POS_Y,MASTER_RIGHT_POS_Z,MASTER_RIGHT_ROT_R11,MASTER_RIGHT_ROT_R12,MASTER_RIGHT_ROT_R13,MASTER_RIGHT_ROT_R21,MASTER_RIGHT_ROT_R22,MASTER_RIGHT_ROT_R23,MASTER_RIGHT_ROT_R31,MASTER_RIGHT_ROT_R32,MASTER_RIGHT_ROT_R33,MASTER_RIGHT_LIN_VEL_X,MASTER_RIGHT_LIN_VEL_Y,MASTER_RIGHT_LIN_VEL_Z,MASTER_RIGHT_ROT_VEL_X,MASTER_RIGHT_ROT_VEL_Y,MASTER_RIGHT_ROT_VEL_Z,MASTER_RIGHT_GRIPPER_ANGLE,SLAVE_LEFT_POS_X,SLAVE_LEFT_POS_Y,SLAVE_LEFT_POS_Z,SLAVE_LEFT_ROT_R11,SLAVE_LEFT_ROT_R12,SLAVE_LEFT_ROT_R13,SLAVE_LEFT_ROT_R21,SLAVE_LEFT_ROT_R22,SLAVE_LEFT_ROT_R23,SLAVE_LEFT_ROT_R31,SLAVE_LEFT_ROT_R32,SLAVE_LEFT_ROT_R33,SLAVE_LEFT_LIN_VEL_X,SLAVE_LEFT_LIN_VEL_Y,SLAVE_LEFT_LIN_VEL_Z,SLAVE_LEFT_ROT_VEL_X,SLAVE_LEFT_ROT_VEL_Y,SLAVE_LEFT_ROT_VEL_Z,SLAVE_LEFT_GRIPPER_ANGLE,SLAVE_RIGHT_POS_X,SLAVE_RIGHT_POS_Y,SLAVE_RIGHT_POS_Z,SLAVE_RIGHT_ROT_R11,SLAVE_RIGHT_ROT_R12,SLAVE_RIGHT_ROT_R13,SLAVE_RIGHT_ROT_R21,SLAVE_RIGHT_ROT_R22,SLAVE_RIGHT_ROT_R23,SLAVE_RIGHT_ROT_R31,SLAVE_RIGHT_ROT_R32,SLAVE_RIGHT_ROT_R33,SLAVE_RIGHT_LIN_VEL_X,SLAVE_RIGHT_LIN_VEL_Y,SLAVE_RIGHT_LIN_VEL_Z,SLAVE_RIGHT_ROT_VEL_X,SLAVE_RIGHT_ROT_VEL_Y,SLAVE_RIGHT_ROT_VEL_Z,SLAVE_RIGHT_GRIPPER_ANGLE
0,0.111180,-0.033020,0.415991,-0.421266,0.609012,-0.672075,-0.699657,-0.689689,-0.186497,-0.576585,0.390896,0.717480,0.014905,0.003267,0.002176,0.000944,-0.014697,0.029520,0.000673,-0.127366,-0.019917,0.410877,0.390984,0.710304,0.585313,-0.647345,0.664323,-0.373569,-0.654647,-0.233744,0.718794,-0.048999,-0.034081,0.095535,-0.268031,0.579878,-0.195054,-0.752383,0.031305,0.032123,-0.006351,-0.271960,-0.777115,0.567564,0.718951,-0.556117,-0.416942,0.639645,0.294659,0.709950,-0.024533,-0.017431,0.047554,-0.092557,0.960642,-0.439861,-0.882220,0.065262,0.019514,-0.062570,-0.531248,0.545307,-0.648394,-0.560945,-0.799939,-0.213160,-0.634914,0.250473,0.730853,0.007652,0.006507,-0.003909,0.046381,-0.039598,0.080345,-0.214419
1,0.111543,-0.032800,0.415891,-0.421579,0.608902,-0.671979,-0.700449,-0.689239,-0.185181,-0.575394,0.391858,0.717911,0.015593,0.014403,-0.006863,0.038299,-0.036630,0.075055,0.011011,-0.128161,-0.020432,0.412530,0.375634,0.711958,0.593302,-0.650642,0.658520,-0.378089,-0.660327,-0.244910,0.709825,-0.036836,-0.023667,0.084838,0.415940,0.743661,-0.802150,-0.774156,0.030874,0.031846,-0.005456,-0.255359,-0.776608,0.575908,0.721716,-0.549475,-0.420953,0.643363,0.308149,0.700804,-0.018481,-0.011878,0.042426,0.478164,0.702775,-0.879348,-0.903611,0.065449,0.019624,-0.062620,-0.531490,0.545168,-0.648312,-0.561789,-0.799682,-0.211898,-0.633964,0.251593,0.731292,0.014519,0.001618,0.001034,0.007131,-0.039824,0.088421,-0.203969
2,0.112342,-0.032401,0.415759,-0.424283,0.607637,-0.671422,-0.702506,-0.688674,-0.179403,-0.570882,0.394801,0.719898,0.015385,0.005576,0.003730,0.002509,-0.023925,0.056777,0.020867,-0.129463,-0.021399,0.415799,0.358887,0.707503,0.608794,-0.642761,0.660322,-0.388286,-0.677136,-0.252858,0.690951,-0.024175,-0.017078,0.071655,-0.003651,0.615323,-0.252731,-0.803653,0.030240,0.031386,-0.003874,-0.240160,-0.770898,0.589948,0.713921,-0.552056,-0.430756,0.657753,0.317726,0.682942,-0.011580,-0.012894,0.041156,1.945516,1.457102,-1.589217,-0.870626,0.065850,0.019831,-0.062687,-0.533921,0.543392,-0.647805,-0.563859,-0.799740,-0.206105,-0.630072,0.255227,0.733394,0.014602,0.006128,-0.004220,0.045144,-0.053541,0.108663,-0.184047
3,0.113310,-0.032094,0.415662,-0.426768,0.606486,-0.670888,-0.704741,-0.687873,-0.173617,-0.566258,0.397950,0.721814,0.028761,0.002474,0.001518,0.001836,-0.029373,0.058997,0.007633,-0.129919,-0.022448,0.418787,0.353248,0.705473,0.614422,-0.627453,0.665846,-0.403591,-0.694247,-0.243850,0.677068,0.004305,-0.030264,0.077260,-0.169809,0.505646,-0.166553,-0.862160,0.029996,0.030874,-0.002376,-0.234423,-0.769138,0.594534,0.698967,-0.558404,-0.446798,0.675640,0.310821,0.668505,0.001570,-0.011164,0.033100,0.514555,0.713481,-0.418331,-0.884016,0.066329,0.019989,-0.062732,-0.536165,0.541769,-0.647312,-0.566158,-0.799595,-0.200277,-0.626092,0.259099,0.735442,0.014518,0.001836,0.001153,0.010400,-0.041345,0.091345,-0.185680
4,0.114262,-0.031781,0.415619,-0.430317,0.607002,-0.668147,-0.707102,-0.686711,-0.168541,-0.560601,0.399164,0.725550,0.029019,0.003862,0.002437,-0.184547,0.136950,-0.240321,-0.002118,-0.129676,-0.023717,0.421465,0.356699,0.706821,0.610869,-0.611420,0.671060,-0.419258,-0.706688,-0.224849,0.670744,0.017474,-0.029637,0.060629,1.989740,0.543088,-1.680500,-0.888722,0.030115,0.030221,-0.000976,-0.237094,-0.769884,0.592507,0.683769,-0.565492,-0.461170,0.690106,0.295797,0.660498,0.008738,-0.015298,0.030011,1.980222,0.532770,-1.673215,-0.890711,0.066799,0.020138,-0.062753,-0.539308,0.542123,-0.644398,-0.568623,-0.798861,-0.196181,-0.621140,0.260618,0.739096,0.014468,0.001683,0.001018,-2.019298,0.839852,-1.606168,-0.199723
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1730,0.116785,0.036535,0.483924,-0.255972,0.861855,-0.437870,-0.964647,-0.257075,0.057798,-0.062441,0.436111,0.897739,0.010251,-0.003671,-0.001753,0.000301,-0.016557,0.029157,-1.043436,-0.097328,0.040237,0.452205,0.451944,0.546958,0.704681,-0.833806,0.539661,0.116049,-0.317362,-0.640697,0.699037,0.002232,-0.009142,-0.003001,-0.000652,0.008726,-0.027457,-1.063313,0.046289,0.062180,0.014383,-0.350208,-0.628017,0.694945,0.902900,-0.423767,0.072049,0.249247,0.652698,0.715443,0.001042,-0.004259,-0.001399,-0.001172,0.008408,-0.027208,-0.841724,0.068073,0.054301,-0.028602,-0.413876,0.815473,-0.404609,-0.899961,-0.433425,0.047022,-0.137023,0.383593,0.913279,-0.000198,-0.000905,-0.000218,0.005503,0.013254,0.001610,-0.869705
1731,0.116884,0.036420,0.483817,-0.255851,0.861816,-0.438017,-0.964666,-0.257052,0.057591,-0.062650,0.436202,0.897680,0.009776,-0.005865,-0.002284,0.000984,-0.014715,0.029553,-1.021469,-0.097209,0.039996,0.452114,0.451629,0.547090,0.704780,-0.833954,0.539487,0.115788,-0.317420,-0.640730,0.698979,0.001268,-0.005188,-0.001709,0.000000,0.000000,0.000000,-1.060212,0.046350,0.062054,0.014336,-0.349854,-0.628115,0.695034,0.903025,-0.423547,0.071782,0.249292,0.652747,0.715383,0.000603,-0.002463,-0.000812,-0.000115,-0.000020,-0.000082,-0.841561,0.068127,0.054247,-0.028655,-0.413730,0.815531,-0.404640,-0.899994,-0.433386,0.046746,-0.137243,0.383514,0.913279,0.004871,-0.003010,-0.001161,0.001081,-0.014446,0.029643,-0.869868
1732,0.116952,0.036378,0.483691,-0.255682,0.861787,-0.438174,-0.964689,-0.257036,0.057262,-0.062968,0.436269,0.897625,-0.001138,0.002511,-0.012571,0.033771,-0.005107,-0.009712,-1.010911,-0.097176,0.039894,0.452090,0.451295,0.545072,0.706555,-0.834071,0.539031,0.117070,-0.317590,-0.642830,0.696972,0.001108,-0.004533,-0.001495,-0.006689,0.014412,0.004747,-1.060636,0.046366,0.062006,0.014325,-0.349757,-0.625909,0.697071,0.903118,-0.423099,0.073235,0.249091,0.655152,0.713252,0.000613,-0.002507,-0.000829,0.004568,-0.003395,-0.031847,-0.842214,0.068162,0.054228,-0.028713,-0.413554,0.815546,-0.404792,-0.900030,-0.433346,0.046437,-0.137544,0.383529,0.913228,-0.000523,-0.002397,-0.000582,-0.000003,0.000036,0.000046,-0.868562
1733,0.117057,0.036289,0.483460,-0.260417,0.860220,-0.438463,-0.963208,-0.262668,0.056632,-0.066138,0.436009,0.897524,-0.000678,0.004611,-0.012062,0.036018,-0.011974,0.018189,-1.008063,-0.097182,0.039815,0.452065,0.451189,0.545100,0.706601,-0.834122,0.538968,0.116997,-0.317607,-0.642859,0.696937,0.000316,-0.001294,-0.000427,-0.000001,0.000003,0.000001,-1.059068,0.046363,0.061966,0.014312,-0.349627,-0.626144,0.696924,0.903161,-0.423046,0.073010,0.249116,0.654961,0.713418,0.005594,0.000587,0.000048,0.002346,-0.016001,0.028929,-0.843520,0.068213,0.054176,-0.028830,-0.417953,0.813127,-0.405141,-0.897519,-0.438610,0.045602,-0.140619,0.382681,0.913116,-0.000447,-0.002058,-0.000502,-0.000395,0.000010,0.000072,-0.870521
1734,0.117186,0.036200,0.483347,-0.259871,0.860239,-0.438751,-0.963336,-0.262298,0.056184,-0.066436,0.436194,0.897412,0.010174,-0.004107,-0.001860,0.000984,-0.014715,0.029553,-1.005905,-0.097103,0.039842,0.452071,0.451427,0.545048,0.706489,-0.834008,0.539109,0.117155,-0.317566,-0.642785,0.697024,0.010850,0.002549,0.000554,0.002045,-0.015205,0.029245,-1.054079,0.046402,0.061981,0.014316,-0.349873,-0.626128,0.696815,0.903075,-0.423205,0.073161,0.249088,0.654874,0.713508,0.005410,0.001340,0.000299,0.002015,-0.015227,0.029201,-0.844827,0.068277,0.054134,-0.028891,-0.417403,0.813262,-0.405435,-0.897720,-0.438246,0.045141,-0.140969,0.382809,0.913008,0.005100,-0.002002,-0.000919,0.000936,-0.014711,0.029700,-0.872481

In [26]:
#return the rows,columns numbers for the data
df.shape

(1735, 76)

In [27]:
#summary of dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1735 entries, 0 to 1734
Data columns (total 76 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   MASTER_LEFT_POS_X           1735 non-null   float64
 1   MASTER_LEFT_POS_Y           1735 non-null   float64
 2   MASTER_LEFT_POS_Z           1735 non-null   float64
 3   MASTER_LEFT_ROT_R11         1735 non-null   float64
 4   MASTER_LEFT_ROT_R12         1735 non-null   float64
 5   MASTER_LEFT_ROT_R13         1735 non-null   float64
 6   MASTER_LEFT_ROT_R21         1735 non-null   float64
 7   MASTER_LEFT_ROT_R22         1735 non-null   float64
 8   MASTER_LEFT_ROT_R23         1735 non-null   float64
 9   MASTER_LEFT_ROT_R31         1735 non-null   float64
 10  MASTER_LEFT_ROT_R32         1735 non-null   float64
 11  MASTER_LEFT_ROT_R33         1735 non-null   float64
 12  MASTER_LEFT_LIN_VEL_X       1735 non-null   float64
 13  MASTER_LEFT_LIN_VEL_Y       1735 non-null   float64
 14  MASTER_LEFT_LIN_VEL_Z       1735 non-null   float64
 15  MASTER_LEFT_ROT_VEL_X       1735 non-null   float64
 16  MASTER_LEFT_ROT_VEL_Y       1735 non-null   float64
 17  MASTER_LEFT_ROT_VEL_Z       1735 non-null   float64
 18  MASTER_LEFT_GRIPPER_ANGLE   1735 non-null   float64
 19  MASTER_RIGHT_POS_X          1735 non-null   float64
 20  MASTER_RIGHT_POS_Y          1735 non-null   float64
 21  MASTER_RIGHT_POS_Z          1735 non-null   float64
 22  MASTER_RIGHT_ROT_R11        1735 non-null   float64
 23  MASTER_RIGHT_ROT_R12        1735 non-null   float64
 24  MASTER_RIGHT_ROT_R13        1735 non-null   float64
 25  MASTER_RIGHT_ROT_R21        1735 non-null   float64
 26  MASTER_RIGHT_ROT_R22        1735 non-null   float64
 27  MASTER_RIGHT_ROT_R23        1735 non-null   float64
 28  MASTER_RIGHT_ROT_R31        1735 non-null   float64
 29  MASTER_RIGHT_ROT_R32        1735 non-null   float64
 30  MASTER_RIGHT_ROT_R33        1735 non-null   float64
 31  MASTER_RIGHT_LIN_VEL_X      1735 non-null   float64
 32  MASTER_RIGHT_LIN_VEL_Y      1735 non-null   float64
 33  MASTER_RIGHT_LIN_VEL_Z      1735 non-null   float64
 34  MASTER_RIGHT_ROT_VEL_X      1735 non-null   float64
 35  MASTER_RIGHT_ROT_VEL_Y      1735 non-null   float64
 36  MASTER_RIGHT_ROT_VEL_Z      1735 non-null   float64
 37  MASTER_RIGHT_GRIPPER_ANGLE  1735 non-null   float64
 38  SLAVE_LEFT_POS_X            1735 non-null   float64
 39  SLAVE_LEFT_POS_Y            1735 non-null   float64
 40  SLAVE_LEFT_POS_Z            1735 non-null   float64
 41  SLAVE_LEFT_ROT_R11          1735 non-null   float64
 42  SLAVE_LEFT_ROT_R12          1735 non-null   float64
 43  SLAVE_LEFT_ROT_R13          1735 non-null   float64
 44  SLAVE_LEFT_ROT_R21          1735 non-null   float64
 45  SLAVE_LEFT_ROT_R22          1735 non-null   float64
 46  SLAVE_LEFT_ROT_R23          1735 non-null   float64
 47  SLAVE_LEFT_ROT_R31          1735 non-null   float64
 48  SLAVE_LEFT_ROT_R32          1735 non-null   float64
 49  SLAVE_LEFT_ROT_R33          1735 non-null   float64
 50  SLAVE_LEFT_LIN_VEL_X        1735 non-null   float64
 51  SLAVE_LEFT_LIN_VEL_Y        1735 non-null   float64
 52  SLAVE_LEFT_LIN_VEL_Z        1735 non-null   float64
 53  SLAVE_LEFT_ROT_VEL_X        1735 non-null   float64
 54  SLAVE_LEFT_ROT_VEL_Y        1735 non-null   float64
 55  SLAVE_LEFT_ROT_VEL_Z        1735 non-null   float64
 56  SLAVE_LEFT_GRIPPER_ANGLE    1735 non-null   float64
 57  SLAVE_RIGHT_POS_X           1735 non-null   float64
 58  SLAVE_RIGHT_POS_Y           1735 non-null   float64
 59  SLAVE_RIGHT_POS_Z           1735 non-null   float64
 60  SLAVE_RIGHT_ROT_R11         1735 non-null   float64
 61  SLAVE_RIGHT_ROT_R12         1735 non-null   float64
 62  SLAVE_RIGHT_ROT_R13         1735 non-null   float64
 63  SLAVE_RIGHT_ROT_R21         1735 non-null   float64
 64  SLAVE_RIGHT_ROT_R22         1735 non-null   float64
 65  SLAVE_RIGHT_ROT_R23         1735 non-null   float64
 66  SLAVE_RIGHT_ROT_R31         1735 non-null   float64
 67  SLAVE_RIGHT_ROT_R32         1735 non-null   float64
 68  SLAVE_RIGHT_ROT_R33         1735 non-null   float64
 69  SLAVE_RIGHT_LIN_VEL_X       1735 non-null   float64
 70  SLAVE_RIGHT_LIN_VEL_Y       1735 non-null   float64
 71  SLAVE_RIGHT_LIN_VEL_Z       1735 non-null   float64
 72  SLAVE_RIGHT_ROT_VEL_X       1735 non-null   float64
 73  SLAVE_RIGHT_ROT_VEL_Y       1735 non-null   float64
 74  SLAVE_RIGHT_ROT_VEL_Z       1735 non-null   float64
 75  SLAVE_RIGHT_GRIPPER_ANGLE   1735 non-null   float64
dtypes: float64(76)
memory usage: 1.0 MB

In [8]:
pd.set_option("display.max_columns", 76)

In [9]:
result_knot_df = pd.read_csv("processed/trial_results/meta_file_Knot_Tying.csv")

In [10]:
result_knot_df

,trial,self_skil,grs_score,tissue_respect,handling,time_and_motion,flow,performance,quality
0,Knot_Tying_B001,N,13,2,2,2,2,2,3
1,Knot_Tying_B002,N,9,1,1,2,2,1,2
2,Knot_Tying_B003,N,11,1,2,2,2,2,2
3,Knot_Tying_B004,N,8,1,2,1,1,1,2
4,Knot_Tying_C001,I,20,4,3,3,3,3,4
5,Knot_Tying_C002,I,22,4,3,3,4,4,4
6,Knot_Tying_C003,I,18,3,3,3,3,3,3
7,Knot_Tying_C004,I,20,4,3,3,3,3,4
8,Knot_Tying_C005,I,20,4,3,3,3,3,4
9,Knot_Tying_D001,E,14,3,1,2,3,2,3
10,Knot_Tying_D002,E,16,3,2,2,3,3,3
11,Knot_Tying_D003,E,12,1,2,2,2,2,3
12,Knot_Tying_D004,E,19,3,3,3,4,3,3
13,Knot_Tying_D005,E,18,3,3,3,3,3,3
14,Knot_Tying_E001,E,18,4,2,2,3,3,4
15,Knot_Tying_E002,E,19,3,3,3,3,3,4
16,Knot_Tying_E003,E,22,3,4,3,4,4,4
17,Knot_Tying_E004,E,18,2,3,3,4,3,3
18,Knot_Tying_E005,E,21,3,4,3,4,3,4
19,Knot_Tying_F001,I,16,3,2,2,3,3,3
20,Knot_Tying_F002,I,20,4,3,3,3,3,4
21,Knot_Tying_F003,I,10,2,1,1,2,1,3
22,Knot_Tying_F004,I,10,2,1,1,2,1,3
23,Knot_Tying_F005,I,15,2,3,2,3,2,3
24,Knot_Tying_G001,N,9,2,2,1,1,1,2
25,Knot_Tying_G002,N,11,2,2,1,2,2,2
26,Knot_Tying_G003,N,10,1,2,1,2,2,2
27,Knot_Tying_G004,N,6,1,1,1,1,1,1
28,Knot_Tying_G005,N,11,1,2,1,2,2,3
29,Knot_Tying_H003,N,12,3,2,1,3,2,1
30,Knot_Tying_H004,N,22,3,4,3,4,4,4
31,Knot_Tying_H005,N,18,3,3,3,3,3,3
32,Knot_Tying_I001,N,9,2,1,1,1,1,3
33,Knot_Tying_I002,N,8,1,1,1,2,1,2
34,Knot_Tying_I003,N,8,2,1,1,2,1,1
35,Knot_Tying_I005,N,6,1,1,1,1,1,1

In [11]:
result_needle_df = pd.read_csv("processed/trial_results/meta_file_Needle_Passing.csv")

In [12]:
result_needle_df

,trial,self_skil,grs_score,tissue_respect,handling,time_and_motion,flow,performance,quality
0,Needle_Passing_B001,N,8,1,1,1,2,1,2
1,Needle_Passing_B002,N,8,1,1,1,2,1,2
2,Needle_Passing_B003,N,14,2,2,2,3,2,3
3,Needle_Passing_B004,N,19,3,3,3,4,3,3
4,Needle_Passing_C001,I,11,1,2,1,3,2,2
5,Needle_Passing_C002,I,9,1,1,1,3,1,2
6,Needle_Passing_C003,I,7,1,1,1,2,1,1
7,Needle_Passing_C004,I,12,1,2,1,3,2,3
8,Needle_Passing_C005,I,12,1,2,1,3,2,3
9,Needle_Passing_D001,E,9,1,1,1,2,1,3
10,Needle_Passing_D002,E,11,1,2,1,3,2,2
11,Needle_Passing_D003,E,10,1,2,1,3,2,1
12,Needle_Passing_D004,E,12,2,2,1,3,2,2
13,Needle_Passing_D005,E,13,2,2,1,3,2,3
14,Needle_Passing_E001,E,13,2,2,2,3,2,2
15,Needle_Passing_E003,E,13,3,2,1,3,2,2
16,Needle_Passing_E004,E,14,2,3,1,3,2,3
17,Needle_Passing_E005,E,17,3,3,2,3,3,3
18,Needle_Passing_F001,I,22,3,4,3,4,4,4
19,Needle_Passing_F003,I,15,1,4,3,4,2,1
20,Needle_Passing_F004,I,24,4,4,4,4,4,4
21,Needle_Passing_H002,N,19,3,3,2,4,3,4
22,Needle_Passing_H004,N,20,3,3,3,4,3,4
23,Needle_Passing_H005,N,21,3,4,3,4,3,4
24,Needle_Passing_I002,N,12,1,3,2,3,2,1
25,Needle_Passing_I003,N,14,2,2,2,3,2,3
26,Needle_Passing_I004,N,18,2,3,2,4,3,4
27,Needle_Passing_I005,N,23,4,4,3,4,4,4

In [13]:
result_suture_df = pd.read_csv("processed/trial_results/meta_file_Suturing.csv")

In [14]:
result_suture_df

,trial,self_skil,grs_score,tissue_respect,handling,time_and_motion,flow,performance,quality
0,Suturing_B001,N,13,3,2,1,2,2,3
1,Suturing_B002,N,17,4,2,2,3,3,3
2,Suturing_B003,N,14,3,2,2,2,2,3
3,Suturing_B004,N,10,1,1,2,3,2,1
4,Suturing_B005,N,12,2,2,1,3,2,2
5,Suturing_C001,I,26,4,4,4,5,4,5
6,Suturing_C002,I,20,3,3,3,4,3,4
7,Suturing_C003,I,26,4,4,4,5,4,5
8,Suturing_C004,I,30,5,5,5,5,5,5
9,Suturing_C005,I,17,3,2,2,3,3,4
10,Suturing_D001,E,14,2,2,2,3,2,3
11,Suturing_D002,E,18,2,3,3,4,3,3
12,Suturing_D003,E,14,2,2,2,3,2,3
13,Suturing_D004,E,8,1,1,1,2,1,2
14,Suturing_D005,E,15,2,2,3,3,2,3
15,Suturing_E001,E,17,3,2,3,3,3,3
16,Suturing_E002,E,20,4,2,3,4,3,4
17,Suturing_E003,E,19,3,2,3,4,3,4
18,Suturing_E004,E,19,3,2,3,4,3,4
19,Suturing_E005,E,19,3,2,3,4,3,4
20,Suturing_F001,I,24,4,4,3,4,4,5
21,Suturing_F002,I,26,4,4,4,5,4,5
22,Suturing_F003,I,29,5,5,4,5,5,5
23,Suturing_F004,I,24,3,4,4,5,4,4
24,Suturing_F005,I,29,4,5,5,5,5,5
25,Suturing_G001,N,13,3,1,1,3,1,4
26,Suturing_G002,N,18,3,2,2,4,3,4
27,Suturing_G003,N,13,3,2,1,2,2,3
28,Suturing_G004,N,21,4,3,3,4,3,4
29,Suturing_G005,N,23,4,3,4,4,4,4
30,Suturing_H001,N,14,2,2,2,3,2,3
31,Suturing_H003,N,25,4,4,4,5,4,4
32,Suturing_H004,N,19,3,3,3,4,3,3
33,Suturing_H005,N,21,4,3,3,4,3,4
34,Suturing_I001,N,17,3,3,2,3,3,3
35,Suturing_I002,N,23,4,4,3,4,4,4
36,Suturing_I003,N,17,3,2,2,3,3,4
37,Suturing_I004,N,23,4,4,3,4,4,4
38,Suturing_I005,N,19,3,3,3,4,3,3

In [15]:
df.head()

,MASTER_LEFT_POS_X,MASTER_LEFT_POS_Y,MASTER_LEFT_POS_Z,MASTER_LEFT_ROT_R11,MASTER_LEFT_ROT_R12,MASTER_LEFT_ROT_R13,MASTER_LEFT_ROT_R21,MASTER_LEFT_ROT_R22,MASTER_LEFT_ROT_R23,MASTER_LEFT_ROT_R31,MASTER_LEFT_ROT_R32,MASTER_LEFT_ROT_R33,MASTER_LEFT_LIN_VEL_X,MASTER_LEFT_LIN_VEL_Y,MASTER_LEFT_LIN_VEL_Z,MASTER_LEFT_ROT_VEL_X,MASTER_LEFT_ROT_VEL_Y,MASTER_LEFT_ROT_VEL_Z,MASTER_LEFT_GRIPPER_ANGLE,MASTER_RIGHT_POS_X,MASTER_RIGHT_POS_Y,MASTER_RIGHT_POS_Z,MASTER_RIGHT_ROT_R11,MASTER_RIGHT_ROT_R12,MASTER_RIGHT_ROT_R13,MASTER_RIGHT_ROT_R21,MASTER_RIGHT_ROT_R22,MASTER_RIGHT_ROT_R23,MASTER_RIGHT_ROT_R31,MASTER_RIGHT_ROT_R32,MASTER_RIGHT_ROT_R33,MASTER_RIGHT_LIN_VEL_X,MASTER_RIGHT_LIN_VEL_Y,MASTER_RIGHT_LIN_VEL_Z,MASTER_RIGHT_ROT_VEL_X,MASTER_RIGHT_ROT_VEL_Y,MASTER_RIGHT_ROT_VEL_Z,MASTER_RIGHT_GRIPPER_ANGLE,SLAVE_LEFT_POS_X,SLAVE_LEFT_POS_Y,SLAVE_LEFT_POS_Z,SLAVE_LEFT_ROT_R11,SLAVE_LEFT_ROT_R12,SLAVE_LEFT_ROT_R13,SLAVE_LEFT_ROT_R21,SLAVE_LEFT_ROT_R22,SLAVE_LEFT_ROT_R23,SLAVE_LEFT_ROT_R31,SLAVE_LEFT_ROT_R32,SLAVE_LEFT_ROT_R33,SLAVE_LEFT_LIN_VEL_X,SLAVE_LEFT_LIN_VEL_Y,SLAVE_LEFT_LIN_VEL_Z,SLAVE_LEFT_ROT_VEL_X,SLAVE_LEFT_ROT_VEL_Y,SLAVE_LEFT_ROT_VEL_Z,SLAVE_LEFT_GRIPPER_ANGLE,SLAVE_RIGHT_POS_X,SLAVE_RIGHT_POS_Y,SLAVE_RIGHT_POS_Z,SLAVE_RIGHT_ROT_R11,SLAVE_RIGHT_ROT_R12,SLAVE_RIGHT_ROT_R13,SLAVE_RIGHT_ROT_R21,SLAVE_RIGHT_ROT_R22,SLAVE_RIGHT_ROT_R23,SLAVE_RIGHT_ROT_R31,SLAVE_RIGHT_ROT_R32,SLAVE_RIGHT_ROT_R33,SLAVE_RIGHT_LIN_VEL_X,SLAVE_RIGHT_LIN_VEL_Y,SLAVE_RIGHT_LIN_VEL_Z,SLAVE_RIGHT_ROT_VEL_X,SLAVE_RIGHT_ROT_VEL_Y,SLAVE_RIGHT_ROT_VEL_Z,SLAVE_RIGHT_GRIPPER_ANGLE
0,0.111180,-0.033020,0.415991,-0.421266,0.609012,-0.672075,-0.699657,-0.689689,-0.186497,-0.576585,0.390896,0.717480,0.014905,0.003267,0.002176,0.000944,-0.014697,0.029520,0.000673,-0.127366,-0.019917,0.410877,0.390984,0.710304,0.585313,-0.647345,0.664323,-0.373569,-0.654647,-0.233744,0.718794,-0.048999,-0.034081,0.095535,-0.268031,0.579878,-0.195054,-0.752383,0.031305,0.032123,-0.006351,-0.271960,-0.777115,0.567564,0.718951,-0.556117,-0.416942,0.639645,0.294659,0.709950,-0.024533,-0.017431,0.047554,-0.092557,0.960642,-0.439861,-0.882220,0.065262,0.019514,-0.062570,-0.531248,0.545307,-0.648394,-0.560945,-0.799939,-0.213160,-0.634914,0.250473,0.730853,0.007652,0.006507,-0.003909,0.046381,-0.039598,0.080345,-0.214419
1,0.111543,-0.032800,0.415891,-0.421579,0.608902,-0.671979,-0.700449,-0.689239,-0.185181,-0.575394,0.391858,0.717911,0.015593,0.014403,-0.006863,0.038299,-0.036630,0.075055,0.011011,-0.128161,-0.020432,0.412530,0.375634,0.711958,0.593302,-0.650642,0.658520,-0.378089,-0.660327,-0.244910,0.709825,-0.036836,-0.023667,0.084838,0.415940,0.743661,-0.802150,-0.774156,0.030874,0.031846,-0.005456,-0.255359,-0.776608,0.575908,0.721716,-0.549475,-0.420953,0.643363,0.308149,0.700804,-0.018481,-0.011878,0.042426,0.478164,0.702775,-0.879348,-0.903611,0.065449,0.019624,-0.062620,-0.531490,0.545168,-0.648312,-0.561789,-0.799682,-0.211898,-0.633964,0.251593,0.731292,0.014519,0.001618,0.001034,0.007131,-0.039824,0.088421,-0.203969
2,0.112342,-0.032401,0.415759,-0.424283,0.607637,-0.671422,-0.702506,-0.688674,-0.179403,-0.570882,0.394801,0.719898,0.015385,0.005576,0.003730,0.002509,-0.023925,0.056777,0.020867,-0.129463,-0.021399,0.415799,0.358887,0.707503,0.608794,-0.642761,0.660322,-0.388286,-0.677136,-0.252858,0.690951,-0.024175,-0.017078,0.071655,-0.003651,0.615323,-0.252731,-0.803653,0.030240,0.031386,-0.003874,-0.240160,-0.770898,0.589948,0.713921,-0.552056,-0.430756,0.657753,0.317726,0.682942,-0.011580,-0.012894,0.041156,1.945516,1.457102,-1.589217,-0.870626,0.065850,0.019831,-0.062687,-0.533921,0.543392,-0.647805,-0.563859,-0.799740,-0.206105,-0.630072,0.255227,0.733394,0.014602,0.006128,-0.004220,0.045144,-0.053541,0.108663,-0.184047
3,0.113310,-0.032094,0.415662,-0.426768,0.606486,-0.670888,-0.704741,-0.687873,-0.173617,-0.566258,0.397950,0.721814,0.028761,0.002474,0.001518,0.001836,-0.029373,0.058997,0.007633,-0.129919,-0.022448,0.418787,0.353248,0.705473,0.614422,-0.627453,0.665846,-0.403591,-0.694247,-0.243850,0.677068,0.004305,-0.030264,0.077260,-0.169809,0.505646,-0.166553,-0.862160,0.029996,0.030874,-0.002376,-0.234423,-0.769138,0.594534,0.698967,-0.558404,-0.446798,0.675640,0.310821,0.668505,0.001570,-0.011164,0.033100,0.514555,0.713481,-0.418331,-0.884016,0.066329,0.019989,-0.062732,-0.536165,0.541769,-0.647312,-0.566158,-0.799595,-0.200277,-0.626092,0.259099,0.735442,0.014518,0.001836,0.001153,0.010400,-0.041345,0.091345,-0.185680
4,0.114262,-0.031781,0.415619,-0.430317,0.607002,-0.668147,-0.707102,-0.686711,-0.168541,-0.560601,0.399164,0.725550,0.029019,0.003862,0.002437,-0.184547,0.136950,-0.240321,-0.002118,-0.129676,-0.023717,0.421465,0.356699,0.706821,0.610869,-0.611420,0.671060,-0.419258,-0.706688,-0.224849,0.670744,0.017474,-0.029637,0.060629,1.989740,0.543088,-1.680500,-0.888722,0.030115,0.030221,-0.000976,-0.237094,-0.769884,0.592507,0.683769,-0.565492,-0.461170,0.690106,0.295797,0.660498,0.008738,-0.015298,0.030011,1.980222,0.532770,-1.673215,-0.890711,0.066799,0.020138,-0.062753,-0.539308,0.542123,-0.644398,-0.568623,-0.798861,-0.196181,-0.621140,0.260618,0.739096,0.014468,0.001683,0.001018,-2.019298,0.839852,-1.606168,-0.199723

In [16]:
df.head(10)

,MASTER_LEFT_POS_X,MASTER_LEFT_POS_Y,MASTER_LEFT_POS_Z,MASTER_LEFT_ROT_R11,MASTER_LEFT_ROT_R12,MASTER_LEFT_ROT_R13,MASTER_LEFT_ROT_R21,MASTER_LEFT_ROT_R22,MASTER_LEFT_ROT_R23,MASTER_LEFT_ROT_R31,MASTER_LEFT_ROT_R32,MASTER_LEFT_ROT_R33,MASTER_LEFT_LIN_VEL_X,MASTER_LEFT_LIN_VEL_Y,MASTER_LEFT_LIN_VEL_Z,MASTER_LEFT_ROT_VEL_X,MASTER_LEFT_ROT_VEL_Y,MASTER_LEFT_ROT_VEL_Z,MASTER_LEFT_GRIPPER_ANGLE,MASTER_RIGHT_POS_X,MASTER_RIGHT_POS_Y,MASTER_RIGHT_POS_Z,MASTER_RIGHT_ROT_R11,MASTER_RIGHT_ROT_R12,MASTER_RIGHT_ROT_R13,MASTER_RIGHT_ROT_R21,MASTER_RIGHT_ROT_R22,MASTER_RIGHT_ROT_R23,MASTER_RIGHT_ROT_R31,MASTER_RIGHT_ROT_R32,MASTER_RIGHT_ROT_R33,MASTER_RIGHT_LIN_VEL_X,MASTER_RIGHT_LIN_VEL_Y,MASTER_RIGHT_LIN_VEL_Z,MASTER_RIGHT_ROT_VEL_X,MASTER_RIGHT_ROT_VEL_Y,MASTER_RIGHT_ROT_VEL_Z,MASTER_RIGHT_GRIPPER_ANGLE,SLAVE_LEFT_POS_X,SLAVE_LEFT_POS_Y,SLAVE_LEFT_POS_Z,SLAVE_LEFT_ROT_R11,SLAVE_LEFT_ROT_R12,SLAVE_LEFT_ROT_R13,SLAVE_LEFT_ROT_R21,SLAVE_LEFT_ROT_R22,SLAVE_LEFT_ROT_R23,SLAVE_LEFT_ROT_R31,SLAVE_LEFT_ROT_R32,SLAVE_LEFT_ROT_R33,SLAVE_LEFT_LIN_VEL_X,SLAVE_LEFT_LIN_VEL_Y,SLAVE_LEFT_LIN_VEL_Z,SLAVE_LEFT_ROT_VEL_X,SLAVE_LEFT_ROT_VEL_Y,SLAVE_LEFT_ROT_VEL_Z,SLAVE_LEFT_GRIPPER_ANGLE,SLAVE_RIGHT_POS_X,SLAVE_RIGHT_POS_Y,SLAVE_RIGHT_POS_Z,SLAVE_RIGHT_ROT_R11,SLAVE_RIGHT_ROT_R12,SLAVE_RIGHT_ROT_R13,SLAVE_RIGHT_ROT_R21,SLAVE_RIGHT_ROT_R22,SLAVE_RIGHT_ROT_R23,SLAVE_RIGHT_ROT_R31,SLAVE_RIGHT_ROT_R32,SLAVE_RIGHT_ROT_R33,SLAVE_RIGHT_LIN_VEL_X,SLAVE_RIGHT_LIN_VEL_Y,SLAVE_RIGHT_LIN_VEL_Z,SLAVE_RIGHT_ROT_VEL_X,SLAVE_RIGHT_ROT_VEL_Y,SLAVE_RIGHT_ROT_VEL_Z,SLAVE_RIGHT_GRIPPER_ANGLE
0,0.111180,-0.033020,0.415991,-0.421266,0.609012,-0.672075,-0.699657,-0.689689,-0.186497,-0.576585,0.390896,0.717480,0.014905,0.003267,0.002176,0.000944,-0.014697,0.029520,0.000673,-0.127366,-0.019917,0.410877,0.390984,0.710304,0.585313,-0.647345,0.664323,-0.373569,-0.654647,-0.233744,0.718794,-0.048999,-0.034081,0.095535,-0.268031,0.579878,-0.195054,-0.752383,0.031305,0.032123,-0.006351,-0.271960,-0.777115,0.567564,0.718951,-0.556117,-0.416942,0.639645,0.294659,0.709950,-0.024533,-0.017431,0.047554,-0.092557,0.960642,-0.439861,-0.882220,0.065262,0.019514,-0.062570,-0.531248,0.545307,-0.648394,-0.560945,-0.799939,-0.213160,-0.634914,0.250473,0.730853,0.007652,0.006507,-0.003909,0.046381,-0.039598,0.080345,-0.214419
1,0.111543,-0.032800,0.415891,-0.421579,0.608902,-0.671979,-0.700449,-0.689239,-0.185181,-0.575394,0.391858,0.717911,0.015593,0.014403,-0.006863,0.038299,-0.036630,0.075055,0.011011,-0.128161,-0.020432,0.412530,0.375634,0.711958,0.593302,-0.650642,0.658520,-0.378089,-0.660327,-0.244910,0.709825,-0.036836,-0.023667,0.084838,0.415940,0.743661,-0.802150,-0.774156,0.030874,0.031846,-0.005456,-0.255359,-0.776608,0.575908,0.721716,-0.549475,-0.420953,0.643363,0.308149,0.700804,-0.018481,-0.011878,0.042426,0.478164,0.702775,-0.879348,-0.903611,0.065449,0.019624,-0.062620,-0.531490,0.545168,-0.648312,-0.561789,-0.799682,-0.211898,-0.633964,0.251593,0.731292,0.014519,0.001618,0.001034,0.007131,-0.039824,0.088421,-0.203969
2,0.112342,-0.032401,0.415759,-0.424283,0.607637,-0.671422,-0.702506,-0.688674,-0.179403,-0.570882,0.394801,0.719898,0.015385,0.005576,0.003730,0.002509,-0.023925,0.056777,0.020867,-0.129463,-0.021399,0.415799,0.358887,0.707503,0.608794,-0.642761,0.660322,-0.388286,-0.677136,-0.252858,0.690951,-0.024175,-0.017078,0.071655,-0.003651,0.615323,-0.252731,-0.803653,0.030240,0.031386,-0.003874,-0.240160,-0.770898,0.589948,0.713921,-0.552056,-0.430756,0.657753,0.317726,0.682942,-0.011580,-0.012894,0.041156,1.945516,1.457102,-1.589217,-0.870626,0.065850,0.019831,-0.062687,-0.533921,0.543392,-0.647805,-0.563859,-0.799740,-0.206105,-0.630072,0.255227,0.733394,0.014602,0.006128,-0.004220,0.045144,-0.053541,0.108663,-0.184047
3,0.113310,-0.032094,0.415662,-0.426768,0.606486,-0.670888,-0.704741,-0.687873,-0.173617,-0.566258,0.397950,0.721814,0.028761,0.002474,0.001518,0.001836,-0.029373,0.058997,0.007633,-0.129919,-0.022448,0.418787,0.353248,0.705473,0.614422,-0.627453,0.665846,-0.403591,-0.694247,-0.243850,0.677068,0.004305,-0.030264,0.077260,-0.169809,0.505646,-0.166553,-0.862160,0.029996,0.030874,-0.002376,-0.234423,-0.769138,0.594534,0.698967,-0.558404,-0.446798,0.675640,0.310821,0.668505,0.001570,-0.011164,0.033100,0.514555,0.713481,-0.418331,-0.884016,0.066329,0.019989,-0.062732,-0.536165,0.541769,-0.647312,-0.566158,-0.799595,-0.200277,-0.626092,0.259099,0.735442,0.014518,0.001836,0.001153,0.010400,-0.041345,0.091345,-0.185680
4,0.114262,-0.031781,0.415619,-0.430317,0.607002,-0.668147,-0.707102,-0.686711,-0.168541,-0.560601,0.399164,0.725550,0.029019,0.003862,0.002437,-0.184547,0.136950,-0.240321,-0.002118,-0.129676,-0.023717,0.421465,0.356699,0.706821,0.610869,-0.611420,0.671060,-0.419258,-0.706688,-0.224849,0.670744,0.017474,-0.029637,0.060629,1.989740,0.543088,-1.680500,-0.888722,0.030115,0.030221,-0.000976,-0.237094,-0.769884,0.592507,0.683769,-0.565492,-0.461170,0.690106,0.295797,0.660498,0.008738,-0.015298,0.030011,1.980222,0.532770,-1.673215,-0.890711,0.066799,0.020138,-0.062753,-0.539308,0.542123,-0.644398,-0.568623,-0.798861,-0.196181,-0.621140,0.260618,0.739096,0.014468,0.001683,0.001018,-2.019298,0.839852,-1.606168,-0.199723
5,0.114654,-0.031622,0.415612,-0.430810,0.606802,-0.668012,-0.707958,-0.686239,-0.166867,-0.559142,0.400278,0.726062,0.015389,0.005999,0.003969,0.002608,-0.023372,0.056999,-0.007158,-0.129427,-0.024462,0.422661,0.359859,0.706638,0.609226,-0.603492,0.674316,-0.425475,-0.711889,-0.215452,0.668324,0.019387,-0.044915,0.067286,0.437063,0.164952,-0.591047,-0.918299,0.030231,0.029869,-0.000401,-0.240405,-0.770046,0.590960,0.676016,-0.569716,-0.467359,0.696568,0.287144,0.657526,0.009057,-0.017999,0.028370,1.982056,0.528568,-1.673459,-0.889568,0.067006,0.020222,-0.062759,-0.540202,0.541277,-0.644359,-0.569576,-0.798829,-0.193528,-0.619486,0.262468,0.739828,0.014478,0.001842,0.001138,0.007554,-0.049673,0.086875,-0.205275
6,0.115514,-0.031220,0.415603,-0.434990,0.604858,-0.667066,-0.710608,-0.685529,-0.158294,-0.552505,0.404410,0.728847,0.029635,0.015222,-0.006496,-0.143343,0.024776,-0.045853,-0.019126,-0.128711,-0.026019,0.424687,0.366333,0.705370,0.606831,-0.592514,0.679733,-0.432231,-0.717796,-0.202115,0.666169,0.018108,-0.035845,0.040951,-0.133909,-0.055149,0.103548,-0.966020,0.030597,0.029070,0.000635,-0.246606,-0.769874,0.588625,0.665409,-0.576092,-0.474707,0.704567,0.274611,0.654349,0.009067,-0.018381,0.020186,-0.141504,-0.057444,0.109152,-0.890221,0.067430,0.020418,-0.062761,-0.543824,0.538573,-0.643578,-0.572219,-0.798946,-0.185066,-0.613856,0.267624,0.742668,0.007941,0.004213,0.002779,-0.669149,0.254232,-0.494158,-0.212460
7,0.116356,-0.030747,0.415642,-0.435640,0.604628,-0.666849,-0.712363,-0.684403,-0.155250,-0.549728,0.406650,0.729700,0.029724,0.015973,-0.006025,0.039245,-0.051170,0.104724,-0.030739,-0.127834,-0.027431,0.426153,0.360043,0.710743,0.604321,-0.590928,0.675037,-0.441659,-0.722267,-0.199000,0.662262,0.031752,-0.037292,0.039028,-0.080403,-0.006274,-0.073707,-1.016340,0.031024,0.028370,0.001349,-0.239754,-0.774214,0.585755,0.662821,-0.571387,-0.483926,0.709355,0.272228,0.650158,0.015365,-0.015069,0.013689,0.110071,-0.023227,0.000016,-0.892507,0.067852,0.020656,-0.062740,-0.544520,0.538142,-0.643351,-0.574153,-0.798307,-0.181806,-0.611429,0.270384,0.743670,0.007996,0.004593,0.003018,0.005417,-0.025171,0.059023,-0.222421
8,0.116719,-0.030515,0.415683,-0.437296,0.606020,-0.664498,-0.713257,-0.683703,-0.154231,-0.547250,0.405756,0.732057,0.015984,0.009247,0.006086,-0.531623,0.783914,-0.258362,-0.032239,-0.127320,-0.028055,0.426744,0.362581,0.710189,0.603455,-0.585977,0.677283,-0.444806,-0.725031,-0.193238,0.660947,0.030689,-0.029004,0.028103,-0.094529,-0.080858,0.182045,-1.032214,0.031282,0.028051,0.001646,-0.242214,-0.774077,0.584924,0.658151,-0.574045,-0.487143,0.712859,0.266976,0.648502,0.015409,-0.015253,0.013577,-0.112635,-0.016804,-0.029453,-0.892507,0.068039,0.020774,-0.062725,-0.544702,0.538010,-0.643307,-0.574773,-0.798092,-0.180787,-0.610684,0.271280,0.743957,0.008125,0.009268,-0.002134,-1.997563,0.856966,-1.762992,-0.225360
9,0.117310,-0.030136,0.415684,-0.437476,0.605921,-0.664469,-0.714046,-0.683169,-0.152937,-0.546076,0.406797,0.732355,0.015223,0.013996,-0.007267,0.038268,-0.036309,0.075230,-0.033433,-0.126124,-0.029260,0.427758,0.373267,0.706891,0.600808,-0.565529,0.686800,-0.456527,-0.735789,-0.170269,0.655353,0.031172,-0.032175,0.026152,-0.037521,-0.007462,-0.070702,-1.072219,0.031891,0.027437,0.002163,-0.253472,-0.772133,0.582719,0.638798,-0.585969,-0.498574,0.726421,0.245865,0.641764,0.015584,-0.016250,0.012958,-0.045767,-0.009597,-0.065550,-0.892834,0.068341,0.020973,-0.062718,-0.546488,0.539062,-0.640907,-0.576047,-0.797453,-0.179548,-0.607881,0.271072,0.746324,0.007575,0.006825,-0.003760,0.039567,-0.041330,0.075141,-0.227156

In [17]:
df.tail()

,MASTER_LEFT_POS_X,MASTER_LEFT_POS_Y,MASTER_LEFT_POS_Z,MASTER_LEFT_ROT_R11,MASTER_LEFT_ROT_R12,MASTER_LEFT_ROT_R13,MASTER_LEFT_ROT_R21,MASTER_LEFT_ROT_R22,MASTER_LEFT_ROT_R23,MASTER_LEFT_ROT_R31,MASTER_LEFT_ROT_R32,MASTER_LEFT_ROT_R33,MASTER_LEFT_LIN_VEL_X,MASTER_LEFT_LIN_VEL_Y,MASTER_LEFT_LIN_VEL_Z,MASTER_LEFT_ROT_VEL_X,MASTER_LEFT_ROT_VEL_Y,MASTER_LEFT_ROT_VEL_Z,MASTER_LEFT_GRIPPER_ANGLE,MASTER_RIGHT_POS_X,MASTER_RIGHT_POS_Y,MASTER_RIGHT_POS_Z,MASTER_RIGHT_ROT_R11,MASTER_RIGHT_ROT_R12,MASTER_RIGHT_ROT_R13,MASTER_RIGHT_ROT_R21,MASTER_RIGHT_ROT_R22,MASTER_RIGHT_ROT_R23,MASTER_RIGHT_ROT_R31,MASTER_RIGHT_ROT_R32,MASTER_RIGHT_ROT_R33,MASTER_RIGHT_LIN_VEL_X,MASTER_RIGHT_LIN_VEL_Y,MASTER_RIGHT_LIN_VEL_Z,MASTER_RIGHT_ROT_VEL_X,MASTER_RIGHT_ROT_VEL_Y,MASTER_RIGHT_ROT_VEL_Z,MASTER_RIGHT_GRIPPER_ANGLE,SLAVE_LEFT_POS_X,SLAVE_LEFT_POS_Y,SLAVE_LEFT_POS_Z,SLAVE_LEFT_ROT_R11,SLAVE_LEFT_ROT_R12,SLAVE_LEFT_ROT_R13,SLAVE_LEFT_ROT_R21,SLAVE_LEFT_ROT_R22,SLAVE_LEFT_ROT_R23,SLAVE_LEFT_ROT_R31,SLAVE_LEFT_ROT_R32,SLAVE_LEFT_ROT_R33,SLAVE_LEFT_LIN_VEL_X,SLAVE_LEFT_LIN_VEL_Y,SLAVE_LEFT_LIN_VEL_Z,SLAVE_LEFT_ROT_VEL_X,SLAVE_LEFT_ROT_VEL_Y,SLAVE_LEFT_ROT_VEL_Z,SLAVE_LEFT_GRIPPER_ANGLE,SLAVE_RIGHT_POS_X,SLAVE_RIGHT_POS_Y,SLAVE_RIGHT_POS_Z,SLAVE_RIGHT_ROT_R11,SLAVE_RIGHT_ROT_R12,SLAVE_RIGHT_ROT_R13,SLAVE_RIGHT_ROT_R21,SLAVE_RIGHT_ROT_R22,SLAVE_RIGHT_ROT_R23,SLAVE_RIGHT_ROT_R31,SLAVE_RIGHT_ROT_R32,SLAVE_RIGHT_ROT_R33,SLAVE_RIGHT_LIN_VEL_X,SLAVE_RIGHT_LIN_VEL_Y,SLAVE_RIGHT_LIN_VEL_Z,SLAVE_RIGHT_ROT_VEL_X,SLAVE_RIGHT_ROT_VEL_Y,SLAVE_RIGHT_ROT_VEL_Z,SLAVE_RIGHT_GRIPPER_ANGLE
1730,0.116785,0.036535,0.483924,-0.255972,0.861855,-0.437870,-0.964647,-0.257075,0.057798,-0.062441,0.436111,0.897739,0.010251,-0.003671,-0.001753,0.000301,-0.016557,0.029157,-1.043436,-0.097328,0.040237,0.452205,0.451944,0.546958,0.704681,-0.833806,0.539661,0.116049,-0.317362,-0.640697,0.699037,0.002232,-0.009142,-0.003001,-0.000652,0.008726,-0.027457,-1.063313,0.046289,0.062180,0.014383,-0.350208,-0.628017,0.694945,0.902900,-0.423767,0.072049,0.249247,0.652698,0.715443,0.001042,-0.004259,-0.001399,-0.001172,0.008408,-0.027208,-0.841724,0.068073,0.054301,-0.028602,-0.413876,0.815473,-0.404609,-0.899961,-0.433425,0.047022,-0.137023,0.383593,0.913279,-0.000198,-0.000905,-0.000218,0.005503,0.013254,0.001610,-0.869705
1731,0.116884,0.036420,0.483817,-0.255851,0.861816,-0.438017,-0.964666,-0.257052,0.057591,-0.062650,0.436202,0.897680,0.009776,-0.005865,-0.002284,0.000984,-0.014715,0.029553,-1.021469,-0.097209,0.039996,0.452114,0.451629,0.547090,0.704780,-0.833954,0.539487,0.115788,-0.317420,-0.640730,0.698979,0.001268,-0.005188,-0.001709,0.000000,0.000000,0.000000,-1.060212,0.046350,0.062054,0.014336,-0.349854,-0.628115,0.695034,0.903025,-0.423547,0.071782,0.249292,0.652747,0.715383,0.000603,-0.002463,-0.000812,-0.000115,-0.000020,-0.000082,-0.841561,0.068127,0.054247,-0.028655,-0.413730,0.815531,-0.404640,-0.899994,-0.433386,0.046746,-0.137243,0.383514,0.913279,0.004871,-0.003010,-0.001161,0.001081,-0.014446,0.029643,-0.869868
1732,0.116952,0.036378,0.483691,-0.255682,0.861787,-0.438174,-0.964689,-0.257036,0.057262,-0.062968,0.436269,0.897625,-0.001138,0.002511,-0.012571,0.033771,-0.005107,-0.009712,-1.010911,-0.097176,0.039894,0.452090,0.451295,0.545072,0.706555,-0.834071,0.539031,0.117070,-0.317590,-0.642830,0.696972,0.001108,-0.004533,-0.001495,-0.006689,0.014412,0.004747,-1.060636,0.046366,0.062006,0.014325,-0.349757,-0.625909,0.697071,0.903118,-0.423099,0.073235,0.249091,0.655152,0.713252,0.000613,-0.002507,-0.000829,0.004568,-0.003395,-0.031847,-0.842214,0.068162,0.054228,-0.028713,-0.413554,0.815546,-0.404792,-0.900030,-0.433346,0.046437,-0.137544,0.383529,0.913228,-0.000523,-0.002397,-0.000582,-0.000003,0.000036,0.000046,-0.868562
1733,0.117057,0.036289,0.483460,-0.260417,0.860220,-0.438463,-0.963208,-0.262668,0.056632,-0.066138,0.436009,0.897524,-0.000678,0.004611,-0.012062,0.036018,-0.011974,0.018189,-1.008063,-0.097182,0.039815,0.452065,0.451189,0.545100,0.706601,-0.834122,0.538968,0.116997,-0.317607,-0.642859,0.696937,0.000316,-0.001294,-0.000427,-0.000001,0.000003,0.000001,-1.059068,0.046363,0.061966,0.014312,-0.349627,-0.626144,0.696924,0.903161,-0.423046,0.073010,0.249116,0.654961,0.713418,0.005594,0.000587,0.000048,0.002346,-0.016001,0.028929,-0.843520,0.068213,0.054176,-0.028830,-0.417953,0.813127,-0.405141,-0.897519,-0.438610,0.045602,-0.140619,0.382681,0.913116,-0.000447,-0.002058,-0.000502,-0.000395,0.000010,0.000072,-0.870521
1734,0.117186,0.036200,0.483347,-0.259871,0.860239,-0.438751,-0.963336,-0.262298,0.056184,-0.066436,0.436194,0.897412,0.010174,-0.004107,-0.001860,0.000984,-0.014715,0.029553,-1.005905,-0.097103,0.039842,0.452071,0.451427,0.545048,0.706489,-0.834008,0.539109,0.117155,-0.317566,-0.642785,0.697024,0.010850,0.002549,0.000554,0.002045,-0.015205,0.029245,-1.054079,0.046402,0.061981,0.014316,-0.349873,-0.626128,0.696815,0.903075,-0.423205,0.073161,0.249088,0.654874,0.713508,0.005410,0.001340,0.000299,0.002015,-0.015227,0.029201,-0.844827,0.068277,0.054134,-0.028891,-0.417403,0.813262,-0.405435,-0.897720,-0.438246,0.045141,-0.140969,0.382809,0.913008,0.005100,-0.002002,-0.000919,0.000936,-0.014711,0.029700,-0.872481

In [18]:
df.tail(15)

,MASTER_LEFT_POS_X,MASTER_LEFT_POS_Y,MASTER_LEFT_POS_Z,MASTER_LEFT_ROT_R11,MASTER_LEFT_ROT_R12,MASTER_LEFT_ROT_R13,MASTER_LEFT_ROT_R21,MASTER_LEFT_ROT_R22,MASTER_LEFT_ROT_R23,MASTER_LEFT_ROT_R31,MASTER_LEFT_ROT_R32,MASTER_LEFT_ROT_R33,MASTER_LEFT_LIN_VEL_X,MASTER_LEFT_LIN_VEL_Y,MASTER_LEFT_LIN_VEL_Z,MASTER_LEFT_ROT_VEL_X,MASTER_LEFT_ROT_VEL_Y,MASTER_LEFT_ROT_VEL_Z,MASTER_LEFT_GRIPPER_ANGLE,MASTER_RIGHT_POS_X,MASTER_RIGHT_POS_Y,MASTER_RIGHT_POS_Z,MASTER_RIGHT_ROT_R11,MASTER_RIGHT_ROT_R12,MASTER_RIGHT_ROT_R13,MASTER_RIGHT_ROT_R21,MASTER_RIGHT_ROT_R22,MASTER_RIGHT_ROT_R23,MASTER_RIGHT_ROT_R31,MASTER_RIGHT_ROT_R32,MASTER_RIGHT_ROT_R33,MASTER_RIGHT_LIN_VEL_X,MASTER_RIGHT_LIN_VEL_Y,MASTER_RIGHT_LIN_VEL_Z,MASTER_RIGHT_ROT_VEL_X,MASTER_RIGHT_ROT_VEL_Y,MASTER_RIGHT_ROT_VEL_Z,MASTER_RIGHT_GRIPPER_ANGLE,SLAVE_LEFT_POS_X,SLAVE_LEFT_POS_Y,SLAVE_LEFT_POS_Z,SLAVE_LEFT_ROT_R11,SLAVE_LEFT_ROT_R12,SLAVE_LEFT_ROT_R13,SLAVE_LEFT_ROT_R21,SLAVE_LEFT_ROT_R22,SLAVE_LEFT_ROT_R23,SLAVE_LEFT_ROT_R31,SLAVE_LEFT_ROT_R32,SLAVE_LEFT_ROT_R33,SLAVE_LEFT_LIN_VEL_X,SLAVE_LEFT_LIN_VEL_Y,SLAVE_LEFT_LIN_VEL_Z,SLAVE_LEFT_ROT_VEL_X,SLAVE_LEFT_ROT_VEL_Y,SLAVE_LEFT_ROT_VEL_Z,SLAVE_LEFT_GRIPPER_ANGLE,SLAVE_RIGHT_POS_X,SLAVE_RIGHT_POS_Y,SLAVE_RIGHT_POS_Z,SLAVE_RIGHT_ROT_R11,SLAVE_RIGHT_ROT_R12,SLAVE_RIGHT_ROT_R13,SLAVE_RIGHT_ROT_R21,SLAVE_RIGHT_ROT_R22,SLAVE_RIGHT_ROT_R23,SLAVE_RIGHT_ROT_R31,SLAVE_RIGHT_ROT_R32,SLAVE_RIGHT_ROT_R33,SLAVE_RIGHT_LIN_VEL_X,SLAVE_RIGHT_LIN_VEL_Y,SLAVE_RIGHT_LIN_VEL_Z,SLAVE_RIGHT_ROT_VEL_X,SLAVE_RIGHT_ROT_VEL_Y,SLAVE_RIGHT_ROT_VEL_Z,SLAVE_RIGHT_GRIPPER_ANGLE
1720,0.116972,0.037735,0.484207,-0.257397,0.863695,-0.433386,-0.964572,-0.256459,0.061659,-0.057579,0.432828,0.899651,0.000130,-0.007112,0.011454,-0.020449,-0.035331,0.174367,-1.149383,-0.097741,0.042011,0.452881,0.443617,0.556584,0.702431,-0.844816,0.521195,0.120725,-0.299448,-0.647674,0.700508,0.000274,-0.001122,-0.000359,-0.000005,0.000011,0.000004,-1.140016,0.046081,0.063075,0.014724,-0.340709,-0.636320,0.692107,0.911450,-0.404110,0.077150,0.230596,0.657107,0.717659,0.000221,-0.000908,-0.000290,0.000651,-0.001463,-0.000509,-0.844337,0.068172,0.054911,-0.028463,-0.415681,0.816873,-0.399908,-0.899935,-0.433045,0.050870,-0.131624,0.381038,0.915142,0.000054,-0.003575,0.005718,-0.036023,0.011981,-0.018207,-0.864153
1721,0.116985,0.037407,0.484600,-0.256376,0.863583,-0.434213,-0.964763,-0.256091,0.060185,-0.058912,0.433268,0.899353,-0.000597,-0.010441,0.010673,-0.036025,0.011964,-0.018180,-1.116211,-0.097743,0.041941,0.452899,0.443684,0.556574,0.702397,-0.844818,0.521165,0.120843,-0.299344,-0.647707,0.700522,0.000195,-0.000801,-0.000257,-0.000000,0.000000,0.000000,-1.135477,0.046081,0.063034,0.014731,-0.340776,-0.636329,0.692066,0.911452,-0.404085,0.077261,0.230490,0.657115,0.717686,0.000131,-0.000536,-0.000173,-0.000003,-0.000031,-0.000024,-0.845643,0.068179,0.054749,-0.028266,-0.414526,0.817033,-0.400780,-0.900259,-0.432550,0.049337,-0.133047,0.381258,0.914844,-0.000337,-0.001514,-0.000360,-0.002799,0.007063,-0.028178,-0.862030
1722,0.116966,0.037279,0.484699,-0.256699,0.863568,-0.434051,-0.964700,-0.256215,0.060651,-0.058521,0.433224,0.899400,-0.000827,-0.011491,0.010425,-0.038292,0.018771,-0.046091,-1.106804,-0.097741,0.041932,0.452896,0.443664,0.556580,0.702404,-0.844827,0.521154,0.120829,-0.299347,-0.647711,0.700517,0.000021,-0.000086,-0.000028,-0.000000,0.000000,0.000000,-1.133650,0.046083,0.063028,0.014729,-0.340756,-0.636333,0.692072,0.911459,-0.404071,0.077247,0.230492,0.657119,0.717682,0.000009,-0.000037,-0.000013,-0.000013,-0.000008,-0.000012,-0.846623,0.068169,0.054686,-0.028217,-0.414823,0.816959,-0.400623,-0.900180,-0.432661,0.049794,-0.132654,0.381289,0.914888,-0.000253,-0.001139,-0.000271,-0.000071,0.000050,-0.000058,-0.862193
1723,0.116937,0.037081,0.484770,-0.255899,0.863340,-0.434977,-0.964773,-0.256450,0.058457,-0.060771,0.433539,0.899098,-0.011378,-0.001604,0.000492,-0.000984,0.014715,-0.029553,-1.094038,-0.097763,0.041924,0.452874,0.446878,0.553950,0.702447,-0.841744,0.526137,0.120746,-0.303237,-0.645930,0.700489,0.000128,-0.000525,-0.000168,-0.000000,0.000000,0.000000,-1.127438,0.046071,0.063024,0.014718,-0.344299,-0.634168,0.692307,0.909078,-0.409437,0.077051,0.234593,0.655890,0.717477,0.000081,-0.000332,-0.000106,-0.000149,-0.000148,-0.000041,-0.846949,0.068154,0.054579,-0.028178,-0.414034,0.816907,-0.401543,-0.900210,-0.432841,0.047630,-0.134895,0.381193,0.914600,-0.005716,-0.000912,0.000220,-0.001278,0.014851,-0.029695,-0.864153
1724,0.116897,0.036950,0.484710,-0.255965,0.863325,-0.434968,-0.964751,-0.256541,0.058422,-0.060840,0.433516,0.899105,-0.000990,-0.004516,-0.001075,-0.002267,0.006807,-0.027910,-1.076999,-0.097802,0.041837,0.452848,0.449956,0.551338,0.702536,-0.838706,0.530996,0.120616,-0.307089,-0.644181,0.700422,0.000874,-0.003589,-0.001151,-0.000651,0.008717,-0.027460,-1.105843,0.046050,0.062987,0.014707,-0.347722,-0.632003,0.692575,0.906718,-0.414680,0.076825,0.238643,0.654685,0.717242,0.000304,-0.001245,-0.000398,-0.000169,-0.000084,-0.000133,-0.845643,0.068134,0.054515,-0.028207,-0.414079,0.816887,-0.401539,-0.900180,-0.432910,0.047584,-0.134960,0.381161,0.914604,-0.000373,-0.001709,-0.000408,-0.000012,-0.000003,-0.000007,-0.864479
1725,0.116889,0.036928,0.484616,-0.255721,0.863337,-0.435087,-0.964799,-0.256439,0.058088,-0.061113,0.433552,0.899069,-0.000848,0.003842,-0.012243,0.036027,-0.011957,0.018182,-1.074644,-0.097808,0.041758,0.452823,0.449584,0.551458,0.702681,-0.838887,0.530772,0.120349,-0.307140,-0.644264,0.700323,0.001045,-0.004293,-0.001379,-0.000000,0.000000,0.000000,-1.099909,0.046047,0.062947,0.014694,-0.347311,-0.632081,0.692710,0.906866,-0.414406,0.076548,0.238679,0.654782,0.717141,0.000643,-0.002638,-0.000847,-0.005256,0.068847,-0.217116,-0.845480,0.068130,0.054500,-0.028251,-0.413875,0.816939,-0.401642,-0.900237,-0.432823,0.047295,-0.135203,0.381148,0.914573,-0.000545,-0.002495,-0.000593,-0.002248,0.006815,-0.027904,-0.864806
1726,0.116875,0.036933,0.484369,-0.255541,0.863297,-0.435272,-0.964803,-0.256575,0.057419,-0.061799,0.433550,0.899023,-0.000684,-0.003120,-0.000745,0.000000,0.000000,0.000000,-1.072340,-0.097744,0.041565,0.452750,0.449293,0.551561,0.702785,-0.839021,0.530613,0.120116,-0.307200,-0.644306,0.700258,0.001371,-0.005628,-0.001812,-0.000000,0.000000,0.000000,-1.095816,0.046079,0.062852,0.014658,-0.347022,-0.632145,0.692796,0.906965,-0.414231,0.076333,0.238724,0.654832,0.717081,0.000729,-0.002986,-0.000960,-0.000740,0.008715,-0.027544,-0.845480,0.068122,0.054502,-0.028379,-0.413678,0.816943,-0.401838,-0.900221,-0.432931,0.046591,-0.135906,0.381017,0.914524,-0.000338,-0.001556,-0.000373,0.000002,-0.000008,0.000003,-0.868398
1727,0.116879,0.036903,0.484052,-0.255353,0.863233,-0.435509,-0.964797,-0.256774,0.056613,-0.062647,0.433560,0.898960,-0.001273,0.001899,-0.012707,0.033765,-0.005130,-0.009723,-1.057922,-0.097661,0.041311,0.452587,0.448856,0.551683,0.702969,-0.839164,0.530489,0.119660,-0.307447,-0.644305,0.700151,0.000772,-0.000552,-0.013607,0.034025,0.009466,-0.003628,-1.064940,0.046121,0.062723,0.014581,-0.346549,-0.632221,0.692965,0.907090,-0.414041,0.075884,0.238940,0.654879,0.716966,0.001134,-0.004648,-0.001504,-0.000717,0.008712,-0.027515,-0.839275,0.068126,0.054490,-0.028532,-0.413478,0.816928,-0.402073,-0.900191,-0.433080,0.045798,-0.136716,0.380879,0.914461,0.004705,-0.003745,-0.001333,0.000988,-0.014709,0.029560,-0.868072
1728,0.116848,0.036856,0.483942,-0.255504,0.863188,-0.435511,-0.964742,-0.257017,0.056459,-0.062888,0.433507,0.898969,-0.001128,-0.005147,-0.001236,0.000000,0.000000,0.000000,-1.052064,-0.097583,0.041146,0.452472,0.448664,0.551735,0.703051,-0.839206,0.530478,0.119413,-0.307612,-0.644269,0.700111,0.002598,-0.010653,-0.003455,-0.000653,0.008728,-0.027457,-1.060865,0.046159,0.062645,0.014525,-0.346368,-0.632245,0.693033,0.907115,-0.414027,0.075651,0.239104,0.654864,0.716925,0.001328,-0.005432,-0.001763,-0.000719,0.008714,-0.027488,-0.838295,0.068109,0.054466,-0.028592,-0.413625,0.816851,-0.402080,-0.900085,-0.433319,0.045615,-0.136968,0.380774,0.914467,-0.000619,0.001014,-0.006338,0.033755,-0.005124,-0.009724,-0.866439
1729,0.116770,0.036688,0.483905,-0.255762,0.863161,-0.435413,-0.964676,-0.257236,0.056587,-0.062849,0.433431,0.899007,-0.000858,-0.003913,-0.000942,0.000000,0.000000,0.000000,-1.046253,-0.097433,0.040667,0.452336,0.454375,0.546691,0.703323,-0.833277,0.539867,0.118857,-0.315273,-0.640750,0.699932,0.002934,-0.012022,-0.003924,-0.000651,0.008727,-0.027456,-1.061227,0.046235,0.062402,0.014451,-0.352703,-0.628033,0.693666,0.902491,-0.424152,0.074863,0.247204,0.652432,0.716394,0.001516,-0.006206,-0.002026,-0.001032,0.008184,-0.027455,-0.839928,0.068070,0.054380,-0.028611,-0.413872,0.816773,-0.401983,-0.899979,-0.433526,0.045735,-0.136916,0.380705,0.914503,-0.005791,-0.001214,0.000142,-0.003235,0.021571,-0.057447,-0.868235
1730,0.116785,0.036535,0.483924,-0.255972,0.861855,-0.437870,-0.964647,-0.257075,0.057798,-0.062441,0.436111,0.897739,0.010251,-0.003671,-0.001753,0.000301,-0.016557,0.029157,-1.043436,-0.097328,0.040237,0.452205,0.451944,0.546958,0.704681,-0.833806,0.539661,0.116049,-0.317362,-0.640697,0.699037,0.002232,-0.009142,-0.003001,-0.000652,0.008726,-0.027457,-1.063313,0.046289,0.062180,0.014383,-0.350208,-0.628017,0.694945,0.902900,-0.423767,0.072049,0.249247,0.652698,0.715443,0.001042,-0.004259,-0.001399,-0.001172,0.008408,-0.027208,-0.841724,0.068073,0.054301,-0.028602,-0.413876,0.815473,-0.404609,-0.899961,-0.433425,0.047022,-0.137023,0.383593,0.913279,-0.000198,-0.000905,-0.000218,0.005503,0.013254,0.001610,-0.869705
1731,0.116884,0.036420,0.483817,-0.255851,0.861816,-0.438017,-0.964666,-0.257052,0.057591,-0.062650,0.436202,0.897680,0.009776,-0.005865,-0.002284,0.000984,-0.014715,0.029553,-1.021469,-0.097209,0.039996,0.452114,0.451629,0.547090,0.704780,-0.833954,0.539487,0.115788,-0.317420,-0.640730,0.698979,0.001268,-0.005188,-0.001709,0.000000,0.000000,0.000000,-1.060212,0.046350,0.062054,0.014336,-0.349854,-0.628115,0.695034,0.903025,-0.423547,0.071782,0.249292,0.652747,0.715383,0.000603,-0.002463,-0.000812,-0.000115,-0.000020,-0.000082,-0.841561,0.068127,0.054247,-0.028655,-0.413730,0.815531,-0.404640,-0.899994,-0.433386,0.046746,-0.137243,0.383514,0.913279,0.004871,-0.003010,-0.001161,0.001081,-0.014446,0.029643,-0.869868
1732,0.116952,0.036378,0.483691,-0.255682,0.861787,-0.438174,-0.964689,-0.257036,0.057262,-0.062968,0.436269,0.897625,-0.001138,0.002511,-0.012571,0.033771,-0.005107,-0.009712,-1.010911,-0.097176,0.039894,0.452090,0.451295,0.545072,0.706555,-0.834071,0.539031,0.117070,-0.317590,-0.642830,0.696972,0.001108,-0.004533,-0.001495,-0.006689,0.014412,0.004747,-1.060636,0.046366,0.062006,0.014325,-0.349757,-0.625909,0.697071,0.903118,-0.423099,0.073235,0.249091,0.655152,0.713252,0.000613,-0.002507,-0.000829,0.004568,-0.003395,-0.031847,-0.842214,0.068162,0.054228,-0.028713,-0.413554,0.815546,-0.404792,-0.900030,-0.433346,0.046437,-0.137544,0.383529,0.913228,-0.000523,-0.002397,-0.000582,-0.000003,0.000036,0.000046,-0.868562
1733,0.117057,0.036289,0.483460,-0.260417,0.860220,-0.438463,-0.963208,-0.262668,0.056632,-0.066138,0.436009,0.897524,-0.000678,0.004611,-0.012062,0.036018,-0.011974,0.018189,-1.008063,-0.097182,0.039815,0.452065,0.451189,0.545100,0.706601,-0.834122,0.538968,0.116997,-0.317607,-0.642859,0.696937,0.000316,-0.001294,-0.000427,-0.000001,0.000003,0.000001,-1.059068,0.046363,0.061966,0.014312,-0.349627,-0.626144,0.696924,0.903161,-0.423046,0.073010,0.249116,0.654961,0.713418,0.005594,0.000587,0.000048,0.002346,-0.016001,0.028929,-0.843520,0.068213,0.054176,-0.028830,-0.417953,0.813127,-0.405141,-0.897519,-0.438610,0.045602,-0.140619,0.382681,0.913116,-0.000447,-0.002058,-0.000502,-0.000395,0.000010,0.000072,-0.870521
1734,0.117186,0.036200,0.483347,-0.259871,0.860239,-0.438751,-0.963336,-0.262298,0.056184,-0.066436,0.436194,0.897412,0.010174,-0.004107,-0.001860,0.000984,-0.014715,0.029553,-1.005905,-0.097103,0.039842,0.452071,0.451427,0.545048,0.706489,-0.834008,0.539109,0.117155,-0.317566,-0.642785,0.697024,0.010850,0.002549,0.000554,0.002045,-0.015205,0.029245,-1.054079,0.046402,0.061981,0.014316,-0.349873,-0.626128,0.696815,0.903075,-0.423205,0.073161,0.249088,0.654874,0.713508,0.005410,0.001340,0.000299,0.002015,-0.015227,0.029201,-0.844827,0.068277,0.054134,-0.028891,-0.417403,0.813262,-0.405435,-0.897720,-0.438246,0.045141,-0.140969,0.382809,0.913008,0.005100,-0.002002,-0.000919,0.000936,-0.014711,0.029700,-0.872481

In [28]:
df["MASTER_LEFT_POS_X"]

0       0.111180
1       0.111543
2       0.112342
3       0.113310
4       0.114262
          ...
1730    0.116785
1731    0.116884
1732    0.116952
1733    0.117057
1734    0.117186
Name: MASTER_LEFT_POS_X, Length: 1735, dtype: float64

In [20]:
df["MASTER_LEFT_POS_X"][:6]

0    0.111180
1    0.111543
2    0.112342
3    0.113310
4    0.114262
5    0.114654
Name: MASTER_LEFT_POS_X, dtype: float64

In [21]:
df["MASTER_LEFT_POS_X"][4]

0.114262

In [22]:
type(df["MASTER_LEFT_POS_X"])

pandas.core.series.Series